### ISSUE TITLE
[Feature Request] Submit Tools Within Website

### ISSUE THREAD

**Issue by zero77** [noraj/rawsec-cybersecurity-inventory#5]
Can you consider adding a tool / resource submission box with in the website.
So, users who don't have git or no html can still submit things to the website.
Also, i think this would make things easier and ultimately create less work for you.
Thanks

**Comment by noraj** [comment]
@zero77 The website is fully static (using a static website generator) and data are stored in JSON files. There is no dynamic server side language or database, it is very complicated to make a "submission box" this way. The only way I can think of is a form with some javascript that will trigger the opening of a pull request but I don't know how to implement it or how to prevent bad bots from using it.

**Comment by zero77** [comment]
> The only way I can think of is a form with some javascript that will trigger the opening of a pull request but I don't know how to implement it or how to prevent bad bots from using it.

Some commonly used techniques to stop bots, could be things like check for screen resolution, movement of mouse and JavaScript and completion of a task like a capture.

Also, there may be a github bot or some sort of addon for this or something similar that can be adapted.

**Comment by noraj** [comment]
> Some commonly used techniques to stop bots, could be things like check for screen resolution, movement of mouse and JavaScript and completion of a task like a capture.

That's not the biggest problem.

> Also, there may be a github bot or some sort of addon for this or something similar that can be adapted.

I found only one project doing something near than that. But it was working only for github and the bot was creating a new branch for every PR, I don't remember its name but it has something that made it impossible to use in our case.

**Comment by noraj** [comment]
@zero77 Maybe with a Zapier transformation. Something like google from to gitlab MR. I think the Gitlab MR will be possible but I'll have to find something else than Google Form for submitting the data.

**Comment by zero77** [comment]
Whenever i get time i will have a look to see what's already out there and what can be of use.

**Comment by zero77** [comment]
There is also Adguard, they have created a submission tool on their website though, it only does issues but that may be possible to change but, so far i cant find the code for it.

https://github.com/AdguardTeam/AdguardFilters#how-to-report-a-missed-adfalse-positive

**Comment by noraj** [comment]
> There is also Adguard, they have created a submission tool on their website though, it only does issues but that may be possible to change but, so far i cant find the code for it.

It may be server-side.

**Comment by zero77** [comment]
As of yet, i haven't found anything specifically designed to do this for github.
But, would it be possible to use the github api or email function.

**Comment by noraj** [comment]
@zero77 Have you take a look at https://zapier.com/apps/categories/forms ? Then it can be plugged with a github or gitlab plugin to open MR/PR/issue.

**Comment by zero77** [comment]
@noraj 
> Update: RIP, the Gitlab plugin of Zapier only allow issue creation, no MR.

I thought you had ruled it out, if not i will look into it.

> but I'll have to find something else than Google Form for submitting the data.

What was your reason for ruling out Google form.

**Comment by noraj** [comment]
> I thought you had ruled it out, if not i will look into it.

Zapier Gitlab MR may be added in the future, I asked for it. In between I can create an issue instead.



> What was your reason for ruling out Google form.

There are more than 20 form services so I prefer avoid Google that does a lot of tracking and is bad for privacy.

**Comment by zero77** [comment]
> Zapier Gitlab MR may be added in the future, I asked for it. In between I can create an issue instead.

Currently you can create a github pull requests with lots of the options on there now.
But, it would be nice to have the option for both.

> There are more than 20 form services so I prefer avoid Google that does a lot of tracking and is bad for privacy.

You make a very good point but, sadly based on the link you provided it's the only free one that gives you unlimited submissions, at least from what i have seen so far.

Also, JotForm looks good, as users don't need an account to create submissions but, it gives you a limited amount, even still i would recommend having a look.

**Comment by zero77** [comment]
I will let you know if i spot any others that look good.

**Comment by noraj** [comment]
> Currently you can create a github pull requests with lots of the options on there now.

Yeah but the github repo is just a mirror, I can't merge PR in it.


> You make a very good point but, sadly based on the link you provided it's the only free one that gives you unlimited submissions, at least from what i have seen so far.

Were do you see the price or limits ?

**Comment by zero77** [comment]
> Yeah but the github repo is just a mirror, I can't merge PR in it.

So, are Issues the best option at the moment, as PRs can't be merged.
> Were do you see the price or limits ?

Pick the one you want then click `Learn More` now on their website go to pricing.

**Comment by noraj** [comment]
I'm working on it with a HTML5 conditional form with jQuery + a Zapier catch hook that will open an issue.

**Comment by noraj** [comment]
@zero77 http://inventory.rawsec.ml/submit.html

**Comment by zero77** [comment]
@noraj 
Thanks, but there seams to be a 404 error.

**Comment by noraj** [comment]
Ahhhh Not again. What's happening with gitlab!

**Comment by noraj** [comment]
@zero77 
https://gitlab.com/gitlab-com/support-forum/issues/4567
https://gitlab.com/gitlab-org/gitlab-pages/issues/226

**Comment by zero77** [comment]
@noraj 
It looks really good thanks but, the title `Submit` on its own could be a bit vague to anyone outside of this issue.
Also, perhaps at the top of the page there should be a big message saying submit an entry to this website.

**Comment by noraj** [comment]
I won't encourage people to use this form.

As I put on the page:

> Using this form is not recommended ([see why](https://inventory.rawsec.ml/docs/docs/en/add.html#alternative-submit-form)), prefer another mean of contribution.
