### ISSUE TITLE
search icon not required.

### ISSUE THREAD

**Issue by Nikita-Shah7** [noraj/rawsec-cybersecurity-inventory#54]
https://github.com/noraj/rawsec-cybersecurity-inventory/blob/0124a017486ea4a4d7b82d384c4c5715d3ad7871/pug/index.pug#L12-L13

- Results are fetched when input.value.length is greater than 2. So search icon is not required in index page search bar.

**Comment by noraj** [comment]
I don't see how the two statements are related.

**Comment by noraj** [comment]
- Search triggers only when input is 3 or more to avoid returning false positives
- the magnify icon symbolize the search feature
