### ISSUE TITLE
add tools and resources

### ISSUE THREAD

**Issue by noraj** [noraj/rawsec-cybersecurity-inventory#7]
![HF2020 Events 1600x400 Centered](https://user-images.githubusercontent.com/16578570/91660429-14239a80-ead6-11ea-8882-e29867064356.png)

Here is a list of tools to add: 
https://gitlab.com/rawsec/rawsec-cybersecurity-list/issues/10

## Examples

Adding a tool is as easy as https://github.com/noraj/rawsec-cybersecurity-inventory/commit/a3a526000f9b4bfd36ab7dda19a2a17b666def35

Adding a resource is very simple too https://github.com/noraj/rawsec-cybersecurity-inventory/commit/c2af3fae855dae8c5d14e101c7943003129ed3b7

## How to

[How to contribute?](https://inventory.raw.pm/docs/docs/en/add.html)

**Comment by sudiptog81** [comment]
@noraj PRs are to be made on GitHub/GitLab?

**Comment by noraj** [comment]
> @noraj PRs are to be made on GitHub/GitLab?

MR on Gitlab is easier, PR on Github is possible.

**Comment by WulfPlasma** [comment]
Can I add a few? Specifically King-Phisher, I'll let you know the other ones I'll add from the list in my PR when I'm done.

**Comment by WulfPlasma** [comment]
@noraj #17 Added King Phisher and Gophish

**Comment by noraj** [comment]
@WulfPlasma 
> Can I add a few? Specifically King-Phisher, I'll let you know the other ones I'll add from the list in my PR when I'm done.

Yeah sure

> Added King Phisher and Gophish

I'll check all PR, no need to comment here 😉
